log_level: INFO

listen_host: 0.0.0.0
listen_port: 8740

scaling_interval: 30s

scaling_algorithm:
    algorithm_class: autoscaler.server.scaling.algorithms.linear.LinearScalingAlgorithm
    interval: 10s
    requests_per_instance_interval: 10

cluster_adapter:
    adapter_class: autoscaler.server.scaling.cluster_adapters.kubernetes.KubernetesClusterAdapter
    kubernetes_api_host: 127.0.0.1
    kubernetes_user: admin
    kubernetes_password: pwd123
    kubernetes_namespace: default
    kubernetes_deployment: deployment_name
